apiVersion: v1
kind: Service
metadata:
  name: nginx-service # Nome do recurso service
spec:
  type: LoadBalancer # Tipo do recurso
  selector:
    app: nginx # Noma da TAG de busca do Deployment
  ports:
    - port: 80 # Porta do service
      targetPort: 80 # Porta do container
